version: '2'

services:
  react:
    image: node:13
    command: ["tail", "-f", "/dev/null"]
    working_dir: /usr/src/app
    ports:
      - '3000:3000'
      - '3003:3003'
    volumes:
      - ./app:/usr/src/app
    container_name: demo-apollo
